version: '2'

services:
  postgres:
    container_name: petadmin_database
    image: 'postgres:9.5'
    volumes:
      - 'postgres:/var/lib/postgresql/data'
    environment:
      - POSTGRES_PASSWORD=postgres

  redis:
    container_name: redis
    image: 'redis:3.2-alpine'
    command: redis-server
    ports:
      - '6379:6379'
    volumes:
      - 'redis:/var/lib/redis/data'

  jobs:
    container_name: jobs
    depends_on:
      - 'postgres'
      - 'redis'
      - 'app'
    build: .
    command: bash scripts/start_jobs
    volumes:
      - '.:/petadmin'
    volumes_from:
      - box

  app:
    container_name: petadmin_app
    depends_on:
      - 'postgres'
      - 'redis'
    build: .
    command: bash scripts/start
    ports:
      - '3000:3000'
    volumes:
      - '.:/petadmin'
    volumes_from:
    - box

  box:
    container_name: box
    image: busybox
    volumes:
      - /box

  mailcatcher:
    container_name: mailcatcher
    image: tophfr/mailcatcher
    ports:
      - '1025:25'
      - '1080:80'

volumes:
  redis:
  postgres:
  box: